mex -v -DMATLAB_SIMULATION ...
    sfunction_double.c 			...
	../source/app/acdr.c		...
	../source/app/bldc.c		...
	../source/app/comm.c		...
	../source/app/ctrl.c		...
	../source/app/dpwm.c		...
	../source/app/fault.c		...
	../source/app/lib.c			...
	../source/app/main.c		...
	../source/app/sch.c			...
   	../source/app/linear.c		...
	../source/matlab/fb.c       ...
	../source/matlab/io.c       ...
	../source/matlab/irq.c      ...
	../source/matlab/pwm.c      ...
	../source/matlab/serial.c   ...
	../source/matlab/spd.c      ...
	../source/matlab/sys.c      ...
	../source/matlab/wrapper.c  ...
	;